import {lazy,Suspense,useEffect,useState} from 'react'
import {motion,useReducedMotion,useScroll,useSpring} from 'framer-motion'
import {ArrowDownRight,ArrowRight,Github,Linkedin,Mail,Menu,X} from 'lucide-react'
import {capabilities,experience,projects,research} from './content'
const Scene=lazy(()=>import('./Scene'))
const reveal={hidden:{opacity:0,y:28},show:{opacity:1,y:0,transition:{duration:.65,ease:[.2,.8,.2,1]}}}

function Header(){const[open,setOpen]=useState(false);const links=[['Work','#work'],['Experience','#experience'],['Capabilities','#capabilities'],['Research','#research']];useEffect(()=>{document.body.classList.toggle('menu-open',open);return()=>document.body.classList.remove('menu-open')},[open]);return <header className="header"><a className="brand" href="#top" aria-label="Nevyn Duarte, home"><span className="brand-mark">N/D</span><span>NEVYN DUARTE</span></a><nav className={open?'nav open':'nav'}>{links.map(([l,h])=><a key={h} href={h} onClick={()=>setOpen(false)}>{l}</a>)}<a className="resume" href="/NevynDuarteResume.pdf" target="_blank" rel="noreferrer">Résumé <ArrowDownRight size={14}/></a></nav><button className="menu" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></header>}
function SectionHead({index,kicker,title,copy}){return <motion.div className="section-head" variants={reveal} initial="hidden" whileInView="show" viewport={{once:true,margin:'-15%'}}><div className="section-index">{index} / 06</div><div><p className="kicker">{kicker}</p><h2>{title}</h2>{copy&&<p className="section-copy">{copy}</p>}</div></motion.div>}
function Project({p}){return <motion.article className="project" variants={reveal} initial="hidden" whileInView="show" viewport={{once:true,margin:'-8%'}}><div className="project-top"><span>{p.id} / {p.eyebrow}</span><span>CASE STUDY</span></div><div className="project-grid"><div><h3>{p.title}</h3><p className="project-subtitle">{p.subtitle}</p><p className="project-description">{p.description}</p></div><div className="system-viz" aria-label={`${p.title} system flow`}>{p.flow.map((step,i)=><div className="flow-step" key={step}><span>{String(i+1).padStart(2,'0')}</span>{step}{i<p.flow.length-1&&<i/>}</div>)}</div></div><div className="project-bottom"><div className="metrics">{p.metrics.map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div><div className="tags">{p.stack.map(t=><span key={t}>{t}</span>)}</div></div></motion.article>}

export default function App(){const reduced=useReducedMotion(),{scrollYProgress}=useScroll(),scaleX=useSpring(scrollYProgress,{stiffness:110,damping:28,restDelta:.001});return <><motion.div className="progress" style={{scaleX}}/><Header/><main id="top"><section className="hero"><div className="hero-scene" aria-hidden="true">{!reduced&&<Suspense fallback={null}><Scene/></Suspense>}</div><div className="hero-noise"/><div className="hero-copy"><motion.p className="eyebrow" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.2}}>AI / ML ENGINEER · SYSTEMS BUILDER</motion.p><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:.1}}>I build systems<br/>that <em>think</em>—<br/>and hold up.</motion.h1><motion.p className="hero-dek" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.45}}>Production AI, machine learning, data infrastructure, and quantitative research—engineered from first principles to real-world deployment.</motion.p><motion.div className="hero-actions" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.65}}><a className="button primary" href="#work">Explore systems <ArrowDownRight/></a><a className="button ghost" href="mailto:contact@nevyn.tech">Start a conversation</a></motion.div></div><div className="hero-meta"><span>NEW YORK METRO</span><span>BUILDING AT BRIDGES AI</span><span>MS DATA SCIENCE · CU BOULDER</span></div><a className="scroll-cue" href="#work"><span>SCROLL TO EXPLORE</span><ArrowDownRight/></a></section>
<section className="manifesto"><p>Most portfolios <span>list technology.</span></p><p>This one shows how the pieces <em>become a system.</em></p></section>
<section id="work" className="section projects"><SectionHead index="01" kicker="Selected systems" title="Work with an architecture—not just a screenshot." copy="Four systems across production AI, applied ML, quantitative research, and robotics. Each is framed around the problem, pipeline, and measurable constraints."/>{projects.map(p=><Project key={p.title} p={p}/>)}</section>
<section id="experience" className="section experience"><SectionHead index="02" kicker="Operating history" title="From research to production." copy="A decade of building data products, models, and infrastructure across AI consulting, finance, semiconductors, risk, and robotics."/><div className="timeline">{experience.map(([company,role,period,summary,tags],i)=><motion.article key={company} variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}} className="role"><span className="role-number">{String(i+1).padStart(2,'0')}</span><div><p className="role-period">{period}</p><h3>{company}</h3><h4>{role}</h4></div><p className="role-summary">{summary}</p><div className="tags">{tags.map(t=><span key={t}>{t}</span>)}</div></motion.article>)}</div></section>
<section id="capabilities" className="section"><SectionHead index="03" kicker="Technical range" title="Depth across the whole stack." copy="The useful boundary is not model versus software. It is whether the complete system works, stays observable, and supports a real decision."/><div className="capability-list">{capabilities.map(([n,d],i)=><motion.div key={n} variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><span>0{i+1}</span><h3>{n}</h3><p>{d}</p></motion.div>)}</div></section>
<section id="research" className="section research"><SectionHead index="04" kicker="Research & foundations" title="Theory first. Evidence second. Constraints always." copy="I study the ideas underneath the tools, then pressure-test them against leakage, uncertainty, drift, latency, cost, and maintainability."/><div className="research-grid">{research.map(([n,d],i)=><motion.div key={n} variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><span>DOMAIN {String(i+1).padStart(2,'0')}</span><h3>{n}</h3><p>{d}</p></motion.div>)}</div><div className="reading-strip"><span>WORKING LIBRARY</span><p>The Elements of Statistical Learning · All of Statistics · Deep Learning · Designing Data-Intensive Applications · Advances in Financial Machine Learning · Hidden Technical Debt in ML Systems</p></div></section>
<section className="section education"><SectionHead index="05" kicker="Education" title="Mathematical foundations, applied continuously."/><div className="degree"><span>2023 — 2026</span><div><h3>University of Colorado Boulder</h3><p>Master of Science · Data Science · GPA 3.72</p><small>Machine learning · NLP · statistical modeling · inference · data mining · databases · algorithms</small></div></div><div className="degree"><span>2018 — 2022</span><div><h3>The University of Texas at Austin</h3><p>Bachelor of Science · Mathematics</p><small>Real analysis · probability · linear algebra · statistics · autonomous intelligent robotics</small></div></div></section>
<section id="contact" className="contact"><p className="kicker">06 / Let’s build something consequential</p><h2>Have a difficult system<br/>that needs to become <em>real?</em></h2><a className="contact-link" href="mailto:contact@nevyn.tech">contact@nevyn.tech <ArrowRight/></a><div className="socials"><a href="https://github.com/nevynduarte" target="_blank" rel="noreferrer"><Github/> GitHub</a><a href="https://www.linkedin.com/in/nevynduarte" target="_blank" rel="noreferrer"><Linkedin/> LinkedIn</a><a href="mailto:contact@nevyn.tech"><Mail/> Email</a></div></section></main><footer><span>© 2026 NEVYN DUARTE</span><span>DESIGNED AS A SYSTEM</span><a href="#top">BACK TO TOP ↑</a></footer></>}
