export const projects = [
{id:'01',eyebrow:'Production AI platform',title:'AppRise',subtitle:'News intelligence, from source to screen.',description:'A production content system that ingests licensed media, creates source-grounded scripts, routes human approval, renders avatar video, and schedules distribution—without losing provenance or editorial control.',flow:['Ingest','Understand','Generate','Review','Distribute'],stack:['FastAPI','Next.js','PostgreSQL','Redis','RQ','LLMs','Docker'],metrics:[['15 min','scheduled ingestion'],['3×','render concurrency'],['30 day','retention policy']]},
{id:'02',eyebrow:'Applied ML platform',title:'Property Intelligence',subtitle:'Computer vision and valuation at portfolio scale.',description:'A multi-tenant property intelligence platform combining millions of structured records with YOLOv11, CLIP embeddings, spatial clustering, and gradient-boosted valuation models.',flow:['Acquire','Validate','Embed','Model','Explain'],stack:['PyTorch','YOLOv11','CLIP','LightGBM','PostGIS','ECS'],metrics:[['3M+','records'],['13','services'],['GPU','local training']]},
{id:'03',eyebrow:'Quantitative research',title:'Alternative Data Signals',subtitle:'Research pipelines built for non-stationary markets.',description:'Predictive equity research using transaction and job-posting data at scale, with time-aware validation, reproducible transformations, and analyst-ready outputs.',flow:['Source','Clean','Feature','Validate','Publish'],stack:['PySpark','Databricks','SQL','Python','FactSet','Statistics'],metrics:[['Millions','of observations'],['10+','research reports'],['3×','faster cadence']]},
{id:'04',eyebrow:'Robotics research',title:'Human-Aware Autonomy',subtitle:'Perception and navigation for a mobile robot.',description:'An autonomy stack for person-following using DeepSORT, learned trajectory features, triplet loss, and ROS navigation—recognized with the UT CNS Award for Excellence in Computer Science.',flow:['Sense','Detect','Track','Plan','Navigate'],stack:['Python','C++','ROS','DeepSORT','Computer Vision','Triplet Loss'],metrics:[['8%','accuracy gain'],['Research','co-author'],['Award','UT CNS']]}
]
export const experience=[
['Bridges AI Consulting','Co-Founder, CTO & Lead AI Engineering Consultant','2025 — Now','Own technical scoping, architecture, and production delivery across concurrent AI products. Built agentic content pipelines, multimodal ML platforms, and 13-service cloud systems.',['AI systems','Platform design','ML engineering']],
['M Science · Jefferies','Quantitative Equity Research Associate','2022 — 2023','Developed predictive equity models over millions of alternative-data observations and automated research workflows from quarterly to monthly cadence.',['PySpark','Databricks','Alternative data']],
['Goodfill','Backend Software Engineer · Consultant','2022','Built investor onboarding, FINRA verification, event-driven AWS services, and Interactive Brokers integrations in Go and Python.',['Go','AWS','Trading systems']],
['PerceiveNow','Data Analyst','2022','Deployed Hugging Face NLP models to process 50,000+ research articles, reducing latency and operating cost.',['NLP','AWS Lambda','Hugging Face']],
['Citco','Risk Analysis Intern','2022','Automated regulatory reporting and supported risk and valuation models for portfolios exceeding $10B AUM.',['Risk','SQL','PySpark']],
['AMD','Yield Analysis & Product Development Intern','2021 — 2022','Built adaptive anomaly detection over 100,000+ wafer samples and production dashboards used by 20+ engineers.',['Applied ML','Manufacturing','Power BI']],
['BNY Mellon','Data Analytics Summer Analyst','2021','Built liquidity analytics and automation used across three business units, reducing reconciliation effort by 20%.',['Analytics','Python','Tableau']],
['UT Austin BWI','Undergraduate Research Associate','2019 — 2020','Developed DeepSORT-based person following and robot navigation in Python, C++, and ROS.',['Computer vision','C++','Robotics']],
['Order.co & stae','Software Engineering Intern','2016 — 2017','Built data products, API integrations, and full-stack dashboards with React, D3, Rails, Node, and PostgreSQL.',['Full stack','D3.js','APIs']]
]
export const capabilities=[['AI / ML','PyTorch, TensorFlow, scikit-learn, Hugging Face, XGBoost, LightGBM, computer vision, NLP'],['AI systems','RAG, agents, prompt systems, evaluation, human review, multimodal workflows'],['Data & infra','PostgreSQL, PostGIS, Redis, PySpark, Databricks, AWS, Docker, Cloudflare'],['Engineering','Python, C++, Go, TypeScript, React, FastAPI, distributed and event-driven systems'],['Quantitative','Alternative data, predictive modeling, validation, risk, time series, portfolio research']]
export const research=[['Statistical learning','Bias–variance tradeoffs, regularization, resampling, inference, calibration'],['Machine learning','Representation learning, optimization, deep learning, production evaluation'],['Quantitative finance','Signal research, leakage, non-stationarity, risk-aware decision systems'],['Data systems','Distributed pipelines, data contracts, monitoring, hidden technical debt']]
